name: Docker Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "php:8.3-apache"
          format: "table"

      - name: Build Docker image
        run: |
          cd backend
          docker build -t cloudbox-backend:test .

      - name: Scan built image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "cloudbox-backend:test"
          format: "table"
          exit-code: "0"
          ignore-unfixed: true
          severity: "CRITICAL"

  auto-merge-updates:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.actor == 'renovate[bot]'
    needs: security-scan
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Auto-merge Renovate PRs
        uses: pascalgn/merge-action@v0.15.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          merge_method: squash
          merge_commit_title: "chore: {pull_request_title}"
          merge_commit_message: "Auto-merged security/dependency update"
